language: go

go:
  - 1.7
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify
  
after_success:
  - goveralls -service=travis-ci
